name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3  # Updated to v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-app
        path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: my-app

    - name: Decode SSH key
      run: echo ${{ secrets.SSH_PRIVATE_KEY }} | base64 --decode > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        scp -o StrictHostKeyChecking=no -r target/*.jar $EC2_USER@$EC2_HOST:/home/$EC2_USER/
        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "nohup java -jar /home/$EC2_USER/$(basename target/*.jar) &"
