name: Stop Admin Service on AWS Instance

on:
  workflow_dispatch:

jobs:
  stop-service:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Stop Service on AWS Instance
      env:
        AWS_INSTANCE_IP: ${{ secrets.AWS_INSTANCE_IP }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "${SSH_KEY}" > ssh_key.pem
        chmod 600 ssh_key.pem
        ssh -o StrictHostKeyChecking=no -i ssh_key.pem ${SSH_USERNAME}@${AWS_INSTANCE_IP} 'sudo fuser -k 8084/tcp'
